import Nav from '@/components/assembled/Nav/index';
import './global.scss';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-svg-gradient="theme-one">
      <body className="flex flex-col h-screen relative pt-[3.75rem] md:pt-[3.25rem]">
        <Nav />
        <div className="flex flex-col flex-1">{children}</div>
      </body>
    </html>
  );
}
