import Nav from '@/components/assembled/Nav/index';
import './global.scss';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <Nav />
          <div className="flex flex-col flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
